"""Generate `RULES.md` from the registry.

Documentation that is written by hand drifts from the code. This is written by the
code, and `tests/test_catalogue.py` fails if the committed file falls behind — so the
catalogue cannot claim a rule that does not exist, or miss one that does.
"""

from __future__ import annotations

import sys
from pathlib import Path

from kavach.rules import (
    ALL_RULES,
    BLOCKED_RULES,
    CENSUS_RULES,
    COMPLETENESS_RULES,
    CONSERVATION_RULES,
    GRAMMAR_RULES,
)

CATALOGUE_PATH = Path(__file__).resolve().parents[1] / "RULES.md"

SECTIONS = (
    ("Class 1 — Grammar", GRAMMAR_RULES,
     "The field is its own witness. Free, certain, needs nothing."),
    ("Class 2 — Conservation", CONSERVATION_RULES,
     "Exact integer equality. The double-entry core, and the part nobody else has."),
    ("Class 3 — Completeness", COMPLETENESS_RULES,
     "What is missing, duplicated, or dangling."),
    ("Class 8 — Witness census", CENSUS_RULES,
     "Not a check. Counts how many checks could run at all."),
    ("Classes 4-7 — Blocked", BLOCKED_RULES,
     "Specced, no bodies. Each abstains and names the external fact it lacks."),
)


def render() -> str:
    lines = [
        "# RULES.md — the rule catalogue",
        "",
        "**Generated by `python -m kavach.catalogue`. Do not edit by hand.**",
        "`tests/test_catalogue.py` fails if this file falls behind the registry.",
        "",
        f"{len(ALL_RULES)} rules registered.",
        "",
        "Every rule is a pure function of a view, declares its scope, and returns typed",
        "findings. A rule that cannot run emits `UNVERIFIABLE` — never a pass.",
        "",
    ]
    for title, group, blurb in SECTIONS:
        lines.append(f"## {title}")
        lines.append("")
        lines.append(blurb)
        lines.append("")
        lines.append("| Rule | Scope | What it checks |")
        lines.append("|---|---|---|")
        for declared in group:
            lines.append(
                f"| `{declared.id}` | {declared.scope} | {declared.description} |"
            )
        lines.append("")
    lines.append("## Deliberately not implemented")
    lines.append("")
    lines.append(
        "**Duplicate khata per owner** (HANDOFF_BUILD.md 4). In Bihar, partition is "
        "textual: each heir receives a separate jamabandi on the same survey number "
        "(EVIDENCE.md E1, E3). One person holding several khatas is what a correct "
        "record looks like, so this check would produce false positives at scale. "
        "`C3.no_duplicate_holding` covers the unambiguous case instead."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    CATALOGUE_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {CATALOGUE_PATH} ({len(ALL_RULES)} rules)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
